# Site settings
title: Course Template
email: instructor@email.edu
description: >-
  A template repository for course websites.
baseurl: "" # the subpath of your site
url: "https://example.github.io"
repository: organization/repo
github_username:  username
branch: main

# Build settings
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
theme: jekyll-theme-dinky
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-relative-links

collections:
  modules:
    output: true
    permalink: /modules/:path/
  weeks:
    output: true
    permalink: /week:name/

# Exclude from processing.
exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - .pre-commit-config.yaml
  - jupytext.toml
  - dodo.py
  - Makefile
  - scripts/

defaults:
  -
    scope:
      path: ""
      type: "modules"
    values:
      layout: "module"
  -
    scope:
      path: ""
      type: "weeks"
    values:
      layout: "week"
  -
    scope:
      path: "lecture*.md"
    values:
      layout: "lecture.html"
